import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Pink Heart Teddy Bear',
    price: 599,
    originalPrice: 799,
    image: '/images/products/teddy-pink.jpg',
    rating: 4.8,
    reviews: 256,
    description: 'A soft, huggable teddy bear with a beautiful pink heart embroidered on its chest. Perfect for expressing your love.',
    details: '100% polyester, Machine washable, Hypoallergenic',
    category: 'girlfriend',
    bestFor: ['girlfriend', 'sister'],
    discount: 25,
    inStock: true,
  },
  {
    id: '2',
    name: 'Cute Bunny Plush',
    price: 449,
    originalPrice: 549,
    image: '/images/products/bunny.jpg',
    rating: 4.9,
    reviews: 189,
    description: 'An adorable white and pink bunny with soft fur and floppy ears. Great for kids of all ages.',
    details: '100% soft polyester, Safe for children 3+',
    category: 'kids',
    bestFor: ['kids', 'friend'],
    discount: 18,
    inStock: true,
  },
  {
    id: '3',
    name: 'Puppy Friend Plushie',
    price: 399,
    image: '/images/products/puppy.jpg',
    rating: 4.7,
    reviews: 145,
    description: 'A cheerful brown and white puppy that will bring joy to any child. Perfect cuddle buddy.',
    details: 'Brown and white coloring, Soft and durable',
    category: 'kids',
    bestFor: ['kids'],
    inStock: true,
  },
  {
    id: '4',
    name: 'Angel Bear - Premium',
    price: 899,
    originalPrice: 1199,
    image: '/images/products/angel-bear.jpg',
    rating: 5,
    reviews: 98,
    description: 'An elegant cream-colored teddy bear with soft angel wings and a peaceful expression. A luxury gift.',
    details: 'Premium quality, Wing details, Includes gift box',
    category: 'girlfriend',
    bestFor: ['girlfriend', 'sister'],
    discount: 25,
    inStock: true,
  },
  {
    id: '5',
    name: 'Rainbow Panda Buddy',
    price: 549,
    image: '/images/products/panda.jpg',
    rating: 4.6,
    reviews: 102,
    description: 'A colorful rainbow panda with a big pink heart on its chest. Perfect for kids who love colors.',
    details: 'Multi-colored, Heart design, Soft material',
    category: 'kids',
    bestFor: ['kids', 'friend'],
    inStock: true,
  },
  {
    id: '6',
    name: 'Peaceful Koala',
    price: 479,
    image: '/images/products/koala.jpg',
    rating: 4.8,
    reviews: 134,
    description: 'A sleepy adorable koala with a peaceful expression. Perfect for comfort and relaxation.',
    details: 'Gray coloring, Peaceful design, Hypoallergenic',
    category: 'family',
    bestFor: ['friend', 'sister'],
    inStock: true,
  },
  {
    id: '7',
    name: 'Floral Fox',
    price: 529,
    image: '/images/products/fox.jpg',
    rating: 4.7,
    reviews: 87,
    description: 'A charming orange and white fox with floral patterns. Nature-inspired design for nature lovers.',
    details: 'Orange and white, Floral embroidery, Soft fur',
    category: 'family',
    bestFor: ['friend'],
    inStock: true,
  },
  {
    id: '8',
    name: 'Magical Unicorn',
    price: 699,
    originalPrice: 899,
    image: '/images/products/unicorn.jpg',
    rating: 4.9,
    reviews: 203,
    description: 'A magical pastel unicorn with an iridescent horn and sparkly eyes. Dream come true for kids.',
    details: 'Iridescent horn, Sparkly eyes, Pastel colors',
    category: 'kids',
    bestFor: ['kids', 'girlfriend'],
    discount: 22,
    inStock: true,
  },
  {
    id: '9',
    name: 'Happy Penguin',
    price: 399,
    image: '/images/products/penguin.jpg',
    rating: 4.5,
    reviews: 76,
    description: 'A cheerful black and white penguin wearing a colorful scarf. Fun and playful design.',
    details: 'Black and white, Colorful scarf, Fun design',
    category: 'kids',
    bestFor: ['kids'],
    inStock: true,
  },
  {
    id: '10',
    name: 'Soft Hedgehog',
    price: 349,
    image: '/images/products/hedgehog.jpg',
    rating: 4.6,
    reviews: 92,
    description: 'A super soft pink hedgehog with gentle spikes and a sweet smile. Huggable and adorable.',
    details: 'Pink coloring, Soft spikes, Baby-friendly',
    category: 'kids',
    bestFor: ['kids'],
    inStock: true,
  },
  {
    id: '11',
    name: 'Cozy Cat',
    price: 459,
    image: '/images/products/cat.jpg',
    rating: 4.8,
    reviews: 168,
    description: 'A cozy orange cat plush wearing a warm knitted sweater. Perfect for comfort and warmth.',
    details: 'Orange coloring, Knitted sweater, Warm design',
    category: 'family',
    bestFor: ['friend', 'sister'],
    inStock: true,
  },
  {
    id: '12',
    name: 'Gentle Blue Whale',
    price: 579,
    image: '/images/products/whale.jpg',
    rating: 4.7,
    reviews: 121,
    description: 'A gentle blue whale plush with a friendly expression. Serene and calming for relaxation.',
    details: 'Blue coloring, Ocean theme, Large size',
    category: 'family',
    bestFor: ['friend'],
    inStock: true,
  },
];

